[package]
name = "simple-fdchecker"
version = "0.1.0"
edition = "2021"
authors = ["Panu Eronen"]

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
sha2 = "0.10.2"
walkdir = "2.3.2"

[profile.release]
opt-level = 3